import React, { useState } from 'react';
import { GoogleGenAI } from '@google/genai';
import pptxgen from 'pptxgenjs';

import { Navbar } from './components/Navbar';
import { HeroInput } from './components/HeroInput';
import { DiagramPreview } from './components/DiagramPreview';
import { ComparisonView } from './components/ComparisonView';
import { ActionButtons } from './components/ActionButtons';
import { Footer } from './components/Footer';

export default function App() {
  const [mode, setMode] = useState<'text' | 'image'>('text');
  const [prompt, setPrompt] = useState('');
  const [uploadedImage, setUploadedImage] = useState<string | null>(null);
  const [style, setStyle] = useState('minimal');
  const [loading, setLoading] = useState(false);
  const [isExtracting, setIsExtracting] = useState(false);
  const [extractedData, setExtractedData] = useState<any>(null);
  const [result, setResult] = useState<{ image_url: string } | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleAction = async () => {
    if (mode === 'text') {
      await generateDiagramFromText();
    } else {
      await extractDiagramData();
    }
  };

  const generateDiagramFromText = async () => {
    if (!prompt.trim()) return;
    
    setLoading(true);
    setError(null);
    try {
      const apiKey = (process.env as any).GEMINI_API_KEY;
      const ai = new GoogleGenAI({ apiKey });
      
      const styleModifiers = {
        minimal: "Minimalist flat design, clean vector graphic, monochrome with a single accent color. Lots of whitespace, crisp sans-serif text labels, simple geometric shapes. Pure white background, PPT-ready quality, no clutter.",
        aws: "AWS architecture diagram style, professional cloud infrastructure graphic. Use standard cloud computing icons, isometric or flat 2D layout. Color palette: AWS orange, dark blue, and gray. Pure white background, enterprise presentation quality.",
        dark: "Dark mode architecture diagram, modern futuristic tech aesthetic. Deep charcoal or dark navy background. Glowing neon accents for arrows and borders. High contrast, sleek glassmorphism elements."
      };

      const finalPrompt = `A high-quality, professional software architecture diagram. All components must be clearly labeled with readable text. Clear directional arrows connecting the components.\n\nArchitecture Description:\n${prompt}\n\nVisual Style:\n${styleModifiers[style as keyof typeof styleModifiers]}`;

      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [{ text: finalPrompt }]
        },
        config: {
          imageConfig: {
            aspectRatio: "16:9"
          }
        }
      });

      let base64Image = null;
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          base64Image = part.inlineData.data;
          break;
        }
      }

      if (!base64Image) {
        throw new Error("No image generated by the model.");
      }

      setResult({ image_url: `data:image/png;base64,${base64Image}` });
    } catch (err: any) {
      console.error(err);
      const errorMessage = err.message || "";
      setError(errorMessage || "Failed to generate diagram.");
    } finally {
      setLoading(false);
    }
  };

  const extractDiagramData = async () => {
    if (!uploadedImage) return;
    setIsExtracting(true);
    setError(null);
    setResult(null);
    setExtractedData(null);
    try {
      const apiKey = (process.env as any).GEMINI_API_KEY;
      const ai = new GoogleGenAI({ apiKey });
      
      const base64Data = uploadedImage.split(',')[1];
      const mimeType = uploadedImage.split(';')[0].split(':')[1];
      
      const extractResponse = await ai.models.generateContent({
        model: 'gemini-3.1-pro-preview',
        contents: [
          {
            inlineData: {
              data: base64Data,
              mimeType: mimeType
            }
          },
          "Analyze this diagram image.\n\nExtract:\n1. All text exactly as shown\n2. All components (boxes, services, users, databases)\n3. Relationships (arrows, direction)\n4. Logical flow\n\nReturn STRICT JSON:\n{\n  \"title\": \"\",\n  \"nodes\": [{\"id\": \"\", \"label\": \"\", \"type\": \"\"}],\n  \"edges\": [{\"from\": \"\", \"to\": \"\", \"label\": \"\"}]\n}"
        ],
        config: {
          responseMimeType: "application/json",
        }
      });

      if (!extractResponse.text) throw new Error("Failed to extract data from image.");
      
      const data = JSON.parse(extractResponse.text);
      setExtractedData(data);
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Failed to extract diagram data.");
    } finally {
      setIsExtracting(false);
    }
  };

  const generateRedesign = async () => {
    if (!extractedData) return;
    setLoading(true);
    setError(null);
    try {
      const apiKey = (process.env as any).GEMINI_API_KEY;
      const ai = new GoogleGenAI({ apiKey });
      
      const styleModifiers = {
        minimal: "Minimalist flat design, clean vector graphic, monochrome with a single accent color. Lots of whitespace, crisp sans-serif text labels, simple geometric shapes. Pure white background, PPT-ready quality, no clutter.",
        aws: "AWS architecture diagram style, professional cloud infrastructure graphic. Use standard cloud computing icons, isometric or flat 2D layout. Color palette: AWS orange, dark blue, and gray. Pure white background, enterprise presentation quality.",
        dark: "Dark mode architecture diagram, modern futuristic tech aesthetic. Deep charcoal or dark navy background. Glowing neon accents for arrows and borders. High contrast, sleek glassmorphism elements."
      };

      const architectureDescription = `Title: ${extractedData.title || 'Architecture Diagram'}\nComponents:\n${extractedData.nodes?.map((n:any) => `- ${n.label} (${n.type || 'component'})`).join('\n')}\n\nFlow/Relationships:\n${extractedData.edges?.map((e:any) => `- ${e.from} -> ${e.to} ${e.label ? `(${e.label})` : ''}`).join('\n')}`;
      
      const finalPrompt = `A high-quality, professional software architecture diagram. All components must be clearly labeled with readable text. Clear directional arrows connecting the components.\n\nArchitecture Description:\n${architectureDescription}\n\nVisual Style:\n${styleModifiers[style as keyof typeof styleModifiers]}`;

      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [{ text: finalPrompt }]
        },
        config: {
          imageConfig: {
            aspectRatio: "16:9"
          }
        }
      });

      let base64Image = null;
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          base64Image = part.inlineData.data;
          break;
        }
      }

      if (!base64Image) {
        throw new Error("No image generated by the model.");
      }

      setResult({ image_url: `data:image/png;base64,${base64Image}` });
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Failed to generate diagram.");
    } finally {
      setLoading(false);
    }
  };

  const downloadPNG = () => {
    if (!result?.image_url) return;
    const a = document.createElement('a');
    a.href = result.image_url;
    a.download = 'architecture.png';
    a.click();
  };

  const downloadJPG = () => {
    if (!result?.image_url) return;
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d');
      if (ctx) {
        ctx.fillStyle = '#FFFFFF';
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        ctx.drawImage(img, 0, 0);
        const dataUrl = canvas.toDataURL('image/jpeg', 0.95);
        const a = document.createElement('a');
        a.href = dataUrl;
        a.download = 'architecture.jpg';
        a.click();
      }
    };
    img.src = result.image_url;
  };

  const downloadSVG = () => {
    if (!result?.image_url) return;
    const img = new Image();
    img.onload = () => {
      const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${img.width}" height="${img.height}">
  <image href="${result.image_url}" width="${img.width}" height="${img.height}" />
</svg>`;
      const blob = new Blob([svg], { type: 'image/svg+xml' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'architecture.svg';
      a.click();
      URL.revokeObjectURL(url);
    };
    img.src = result.image_url;
  };

  const downloadPPT = () => {
    if (!result?.image_url) return;
    try {
      const pres = new pptxgen();
      const slide = pres.addSlide();
      const base64Data = result.image_url.replace(/^data:image\/(png|jpg|jpeg);base64,/, "");
      
      slide.addImage({ data: `image/png;base64,${base64Data}`, x: 0.5, y: 0.5, w: 9, h: 5.06 });
      pres.writeFile({ fileName: 'Architecture_Diagram.pptx' });
    } catch (err: any) {
      alert("Error downloading PPT: " + err.message);
    }
  };

  return (
<<<<<<< HEAD
    <div className="h-screen w-full bg-background text-foreground font-sans flex overflow-hidden selection:bg-secondary selection:text-foreground">
      
      {/* 1. Left Sidebar Panel */}
      <Sidebar activeTab={activeTab} setActiveTab={setActiveTab} />
      
      {/* 2. Main Workspace Panel */}
      <main className="flex-1 flex flex-col min-w-0 h-full relative overflow-y-auto overflow-x-hidden custom-scrollbar">
        {activeTab === 'history' ? (
          <HistoryPanel 
            history={history} 
            onClear={clearHistory}
            onSelect={(item) => {
              if (item.type === 'text') {
                setActiveTab('text');
                setPrompt(item.prompt || '');
              } else {
                setActiveTab('image');
                if (item.originalImage) setUploadedImage(item.originalImage);
              }
              setResult({ image_url: item.resultImage });
            }}
=======
    <div className="min-h-screen bg-[#FAFAFA] text-slate-900 font-sans selection:bg-blue-100 flex flex-col">
      <Navbar />
      
      <main className="flex-1 w-full flex flex-col">
        <HeroInput 
          mode={mode}
          setMode={setMode}
          prompt={prompt}
          setPrompt={setPrompt}
          uploadedImage={uploadedImage}
          setUploadedImage={setUploadedImage}
          style={style}
          setStyle={setStyle}
          loading={loading || isExtracting}
          generateDiagram={handleAction}
          error={error}
        />
        
        {mode === 'image' && uploadedImage && (extractedData || result) && !isExtracting ? (
          <ComparisonView 
            originalImage={uploadedImage}
            redesignedImage={result?.image_url || null}
            extractedData={extractedData}
            setExtractedData={setExtractedData}
            onGenerate={generateRedesign}
            isGenerating={loading}
>>>>>>> 9f673154aac585871c4a3622e6dfa4749e99a512
          />
        ) : (
          <DiagramPreview 
            loading={loading || isExtracting}
            result={result}
            mode={mode}
            uploadedImage={uploadedImage}
          />
        )}
        
        <ActionButtons 
          result={result}
          downloadPNG={downloadPNG}
          downloadJPG={downloadJPG}
          downloadSVG={downloadSVG}
          downloadPPT={downloadPPT}
          generateDiagram={handleAction}
          loading={loading || isExtracting}
        />
      </main>

      <Footer />
    </div>
  );
}
