import React, { useState, useEffect } from 'react';
import { GoogleGenAI } from '@google/genai';
import pptxgen from 'pptxgenjs';

import { Sidebar } from './components/Sidebar';
import { SmartControls, SmartControlsState } from './components/SmartControls';
import { HeroInput } from './components/HeroInput';
import { DiagramPreview } from './components/DiagramPreview';
import { ComparisonView } from './components/ComparisonView';
import { ActionBar } from './components/ActionBar';
import { HistoryPanel, HistoryItem } from './components/HistoryPanel';
import { CommandPalette } from './components/CommandPalette';

type TabState = 'text' | 'image' | 'history' | 'templates';

export default function App() {
  const [activeTab, setActiveTab] = useState<TabState>('text');
  const [isCommandOpen, setIsCommandOpen] = useState(false);
  
  // Workspace State
  const [prompt, setPrompt] = useState('');
  const [uploadedImage, setUploadedImage] = useState<string | null>(null);
  
  // Smart Controls
  const [controls, setControls] = useState<SmartControlsState>({
    style: 'minimal',
    layout: 'horizontal',
    improveSpacing: true,
    addGrouping: false
  });

  // Task State
  const [loading, setLoading] = useState(false);
  const [isExtracting, setIsExtracting] = useState(false);
  const [extractedData, setExtractedData] = useState<any>(null);
  const [result, setResult] = useState<{ image_url: string } | null>(null);
  const [error, setError] = useState<string | null>(null);

  // History State
  const [history, setHistory] = useState<HistoryItem[]>([]);

  useEffect(() => {
    const saved = localStorage.getItem('diagramops_history');
    if (saved) {
      try {
        setHistory(JSON.parse(saved));
      } catch(e) {}
    }
  }, []);

  const saveToHistory = (item: Omit<HistoryItem, 'id' | 'timestamp'>) => {
    const newItem: HistoryItem = {
      ...item,
      id: crypto.randomUUID(),
      timestamp: Date.now()
    };
    const newHistory = [newItem, ...history].slice(0, 50); // Keep last 50
    setHistory(newHistory);
    localStorage.setItem('diagramops_history', JSON.stringify(newHistory));
  };

  const clearHistory = () => {
    setHistory([]);
    localStorage.removeItem('diagramops_history');
  };

  const handleAction = async () => {
    if (activeTab === 'text') {
      await generateDiagramFromText();
    } else if (activeTab === 'image') {
      await extractDiagramData();
    }
  };

  const generateDiagramFromText = async () => {
    if (!prompt.trim()) return;
    
    setLoading(true);
    setError(null);
    try {
      const apiKey = (process.env as any).GEMINI_API_KEY;
      if (!apiKey) throw new Error("GEMINI_API_KEY is not defined in the environment.");
      const ai = new GoogleGenAI({ apiKey });
      
      const styleModifiers = {
        minimal: "Minimalist flat design, clean vector graphic, monochrome with a single accent color. Lots of whitespace, crisp sans-serif text labels, simple geometric shapes. Pure white background, PPT-ready quality, no clutter.",
        aws: "AWS architecture diagram style, professional cloud infrastructure graphic. Use standard cloud computing icons, isometric or flat 2D layout. Color palette: AWS orange, dark blue, and gray. Pure white background, enterprise presentation quality.",
        dark: "Dark mode architecture diagram, modern futuristic tech aesthetic. Deep charcoal or dark navy background. Glowing neon accents for arrows and borders. High contrast, sleek glassmorphism elements."
      };

      const finalPrompt = `A high-quality, professional software architecture diagram. All components must be clearly labeled with readable text. Clear directional arrows connecting the components.\n\nArchitecture Description:\n${prompt}\n\nVisual Style:\n${styleModifiers[controls.style as keyof typeof styleModifiers] || styleModifiers.minimal}`;

      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [{ text: finalPrompt }]
        },
        config: {
          imageConfig: {
            aspectRatio: "16:9"
          }
        }
      });

      let base64Image = null;
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          base64Image = part.inlineData.data;
          break;
        }
      }

      if (!base64Image) {
        throw new Error("No image generated by the model.");
      }

      const imageUrl = `data:image/png;base64,${base64Image}`;
      setResult({ image_url: imageUrl });
      saveToHistory({
        type: 'text',
        prompt,
        resultImage: imageUrl
      });
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Failed to generate diagram.");
    } finally {
      setLoading(false);
    }
  };

  const extractDiagramData = async () => {
    if (!uploadedImage) return;
    setIsExtracting(true);
    setError(null);
    setResult(null);
    setExtractedData(null);
    try {
      const apiKey = (process.env as any).GEMINI_API_KEY;
      if (!apiKey) throw new Error("GEMINI_API_KEY is missing.");
      const ai = new GoogleGenAI({ apiKey });
      
      const base64Data = uploadedImage.split(',')[1];
      const mimeType = uploadedImage.split(';')[0].split(':')[1];
      
      const extractResponse = await ai.models.generateContent({
        model: 'gemini-3.1-pro-preview',
        contents: [
          {
            inlineData: {
              data: base64Data,
              mimeType: mimeType
            }
          },
          "Analyze this diagram image.\n\nExtract:\n1. All text exactly as shown\n2. All components (boxes, services, users, databases)\n3. Relationships (arrows, direction)\n4. Logical flow\n\nReturn STRICT JSON:\n{\n  \"title\": \"\",\n  \"nodes\": [{\"id\": \"\", \"label\": \"\", \"type\": \"\"}],\n  \"edges\": [{\"from\": \"\", \"to\": \"\", \"label\": \"\"}]\n}"
        ],
        config: {
          responseMimeType: "application/json",
        }
      });

      if (!extractResponse.text) throw new Error("Failed to extract data from image.");
      
      const data = JSON.parse(extractResponse.text);
      setExtractedData(data);
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Failed to extract diagram data.");
    } finally {
      setIsExtracting(false);
    }
  };

  const generateRedesign = async () => {
    if (!extractedData) return;
    setLoading(true);
    setError(null);
    try {
      const apiKey = (process.env as any).GEMINI_API_KEY;
      const ai = new GoogleGenAI({ apiKey });
      
      const styleModifiers = {
        minimal: "Minimalist flat design, clean vector graphic, monochrome with a single accent color. Lots of whitespace, crisp sans-serif text labels, simple geometric shapes. Pure white background, PPT-ready quality, no clutter.",
        aws: "AWS architecture diagram style, professional cloud infrastructure graphic. Use standard cloud computing icons, isometric or flat 2D layout. Color palette: AWS orange, dark blue, and gray. Pure white background, enterprise presentation quality.",
        dark: "Dark mode architecture diagram, modern futuristic tech aesthetic. Deep charcoal or dark navy background. Glowing neon accents for arrows and borders. High contrast, sleek glassmorphism elements."
      };

      const architectureDescription = `Title: ${extractedData.title || 'Architecture Diagram'}\nComponents:\n${extractedData.nodes?.map((n:any) => `- ${n.label}`).join('\n')}\n\nFlow/Relationships:\n${extractedData.edges?.map((e:any) => `- ${e.from} -> ${e.to} ${e.label ? `(${e.label})` : ''}`).join('\n')}`;
      
      const finalPrompt = `A high-quality, professional software architecture diagram. All components must be clearly labeled with readable text. Clear directional arrows connecting the components.\n\nArchitecture Description:\n${architectureDescription}\n\nVisual Style:\n${styleModifiers[controls.style as keyof typeof styleModifiers] || styleModifiers.minimal}`;

      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [{ text: finalPrompt }]
        },
        config: {
          imageConfig: {
            aspectRatio: "16:9"
          }
        }
      });

      let base64Image = null;
      for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
          base64Image = part.inlineData.data;
          break;
        }
      }

      if (!base64Image) {
        throw new Error("No image generated by the model.");
      }

      const imageUrl = `data:image/png;base64,${base64Image}`;
      setResult({ image_url: imageUrl });
      saveToHistory({
        type: 'image',
        originalImage: uploadedImage || undefined,
        resultImage: imageUrl
      });
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Failed to generate diagram.");
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = (ext: string, mime: string) => {
    if (!result?.image_url) return;
    const a = document.createElement('a');
    a.href = result.image_url;
    a.download = `architecture.${ext}`;
    a.click();
  };

  const downloadPPT = () => {
    if (!result?.image_url) return;
    try {
      const pres = new pptxgen();
      const slide = pres.addSlide();
      const base64Data = result.image_url.replace(/^data:image\/(png|jpg|jpeg);base64,/, "");
      
      slide.addImage({ data: `image/png;base64,${base64Data}`, x: 0.5, y: 0.5, w: 9, h: 5.06 });
      pres.writeFile({ fileName: 'Architecture_Diagram.pptx' });
    } catch (err: any) {
      alert("Error downloading PPT: " + err.message);
    }
  };

  return (
    <div className="h-screen w-full bg-background text-foreground font-sans flex overflow-hidden selection:bg-primary/20 relative">
      
      {/* Animated Mesh Background Layers */}
      <div className="absolute inset-0 z-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-[10%] -left-[10%] w-[40%] h-[40%] rounded-full bg-blue-600/10 blur-[120px] animate-blob" />
        <div className="absolute top-[20%] -right-[10%] w-[50%] h-[50%] rounded-full bg-purple-600/10 blur-[120px] animate-blob animation-delay-2000" />
        <div className="absolute -bottom-[20%] left-[20%] w-[60%] h-[60%] rounded-full bg-pink-600/10 blur-[120px] animate-blob animation-delay-4000" />
        <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 mix-blend-overlay"></div>
      </div>
      
      {/* 1. Left Sidebar Panel */}
      <Sidebar activeTab={activeTab} setActiveTab={setActiveTab} />
      
      {/* 2. Main Workspace Panel */}
      <main className="flex-1 flex flex-col min-w-0 h-full relative overflow-y-auto overflow-x-hidden custom-scrollbar">
        {activeTab === 'history' ? (
          <HistoryPanel 
            history={history} 
            onClear={clearHistory}
            onSelect={(item) => {
              if (item.type === 'text') {
                setActiveTab('text');
                setPrompt(item.prompt || '');
              } else {
                setActiveTab('image');
                if (item.originalImage) setUploadedImage(item.originalImage);
              }
              setResult({ image_url: item.resultImage });
            }}
          />
        ) : activeTab === 'templates' ? (
          <div className="flex-1 flex items-center justify-center text-muted-foreground p-8 text-center flex-col gap-4">
             <div className="w-16 h-16 bg-muted/50 rounded-full flex items-center justify-center">🚧</div>
             <p className="font-semibold text-lg">Templates coming soon</p>
             <p className="text-sm">Premium architecture templates are currently in development.</p>
          </div>
        ) : (
          <>
            <HeroInput 
              mode={activeTab as 'text' | 'image'}
              prompt={prompt}
              setPrompt={setPrompt}
              uploadedImage={uploadedImage}
              setUploadedImage={setUploadedImage}
              loading={loading || isExtracting}
              generateDiagram={handleAction}
              error={error}
            />

            {/* In 'image' mode, if extractedData exists but NO result yet OR we have a result, show Comparison */}
            {activeTab === 'image' && uploadedImage && (extractedData || result) && !isExtracting ? (
              <ComparisonView 
                originalImage={uploadedImage}
                redesignedImage={result?.image_url || null}
                extractedData={extractedData}
                setExtractedData={setExtractedData}
                onGenerate={generateRedesign}
                isGenerating={loading}
              />
            ) : (
              <DiagramPreview 
                loading={loading || isExtracting}
                result={result}
                mode={activeTab as 'text' | 'image'}
                uploadedImage={uploadedImage}
              />
            )}
            
            {/* Soft blank space at bottom for floating action bar */}
            {result && <div className="h-32 w-full" />}
          </>
        )}
        
        {/* Floating Action Bar (Only shows if result exists and not in history view) */}
        {result && activeTab !== 'history' && activeTab !== 'templates' && (
          <ActionBar 
            result={result}
            downloadPNG={() => handleDownload('png', 'image/png')}
            downloadPPT={downloadPPT}
            generateDiagram={activeTab === 'text' ? handleAction : generateRedesign}
            loading={loading || isExtracting}
            prompt={prompt}
          />
        )}
      </main>

      {/* 3. Right Smart Controls Panel */}
      {(activeTab === 'text' || activeTab === 'image') && (
        <SmartControls controls={controls} setControls={setControls} />
      )}

      {/* Global Command Palette */}
      <CommandPalette 
        isOpen={isCommandOpen} 
        setIsOpen={setIsCommandOpen} 
        setActiveTab={setActiveTab}
        generateDiagram={activeTab === 'text' ? handleAction : generateRedesign}
      />
    </div>
  );
}
